2022-04-28 12:43:07 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 34 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 28 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 29 more
2022-04-28 16:10:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE ORDER[*] (ID BIGINT GENERATED BY DEFAULT AS IDENTITY, CREATED_AT TIMESTAMP, CREATED_BY VARCHAR(50), DELETED_AT TIMESTAMP, DELETED_BY VARCHAR(50), IS_DELETED BOOLEAN NOT NULL, UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR(50), CARD_LAST_DATE VARCHAR(255), CARD_NUMBER VARCHAR(255), CARD_OWNER_NAME VARCHAR(255), CCV VARCHAR(255), PAYMENT_STATUS INTEGER, STATUS INTEGER, BASKET_ID BIGINT, PRIMARY KEY (ID))"; expected "identifier"; SQL statement:
create table order (id bigint generated by default as identity, created_at timestamp, created_by varchar(50), deleted_at timestamp, deleted_by varchar(50), is_deleted boolean not null, updated_at timestamp, updated_by varchar(50), card_last_date varchar(255), card_number varchar(255), card_owner_name varchar(255), ccv varchar(255), payment_status integer, status integer, basket_id bigint, primary key (id)) [42001-200]
2022-04-28 16:10:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "ALTER TABLE ORDER[*] ADD CONSTRAINT FKI9DEIURYIQ9CD1U2FQS4QVKRR FOREIGN KEY (BASKET_ID) REFERENCES BASKET"; expected "identifier"; SQL statement:
alter table order add constraint FKi9deiuryiq9cd1u2fqs4qvkrr foreign key (basket_id) references basket [42001-200]
2022-04-28 16:11:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "DROP TABLE IF EXISTS ORDER[*] CASCADE "; expected "identifier"; SQL statement:
drop table if exists order CASCADE  [42001-200]
2022-04-28 16:11:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE ORDER[*] (ID BIGINT GENERATED BY DEFAULT AS IDENTITY, CREATED_AT TIMESTAMP, CREATED_BY VARCHAR(50), DELETED_AT TIMESTAMP, DELETED_BY VARCHAR(50), IS_DELETED BOOLEAN NOT NULL, UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR(50), CARD_LAST_DATE VARCHAR(255), CARD_NUMBER VARCHAR(255), CARD_OWNER_NAME VARCHAR(255), CCV VARCHAR(255), PAYMENT_STATUS INTEGER, STATUS INTEGER, BASKET_ID BIGINT, PRIMARY KEY (ID))"; expected "identifier"; SQL statement:
create table order (id bigint generated by default as identity, created_at timestamp, created_by varchar(50), deleted_at timestamp, deleted_by varchar(50), is_deleted boolean not null, updated_at timestamp, updated_by varchar(50), card_last_date varchar(255), card_number varchar(255), card_owner_name varchar(255), ccv varchar(255), payment_status integer, status integer, basket_id bigint, primary key (id)) [42001-200]
2022-04-28 16:11:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "ALTER TABLE ORDER[*] ADD CONSTRAINT FKI9DEIURYIQ9CD1U2FQS4QVKRR FOREIGN KEY (BASKET_ID) REFERENCES BASKET"; expected "identifier"; SQL statement:
alter table order add constraint FKi9deiuryiq9cd1u2fqs4qvkrr foreign key (basket_id) references basket [42001-200]
2022-04-28 16:12:46 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 34 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 28 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 29 more
2022-04-28 16:12:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "DROP TABLE IF EXISTS ORDER[*] CASCADE "; expected "identifier"; SQL statement:
drop table if exists order CASCADE  [42001-200]
2022-04-28 16:13:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "DROP TABLE IF EXISTS ORDER[*] CASCADE "; expected "identifier"; SQL statement:
drop table if exists order CASCADE  [42001-200]
2022-04-28 16:13:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE ORDER[*] (ID BIGINT GENERATED BY DEFAULT AS IDENTITY, CREATED_AT TIMESTAMP, CREATED_BY VARCHAR(50), DELETED_AT TIMESTAMP, DELETED_BY VARCHAR(50), IS_DELETED BOOLEAN NOT NULL, UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR(50), CARD_LAST_DATE VARCHAR(255), CARD_NUMBER VARCHAR(255), CARD_OWNER_NAME VARCHAR(255), CCV VARCHAR(255), PAYMENT_STATUS INTEGER, STATUS INTEGER, BASKET_ID BIGINT, PRIMARY KEY (ID))"; expected "identifier"; SQL statement:
create table order (id bigint generated by default as identity, created_at timestamp, created_by varchar(50), deleted_at timestamp, deleted_by varchar(50), is_deleted boolean not null, updated_at timestamp, updated_by varchar(50), card_last_date varchar(255), card_number varchar(255), card_owner_name varchar(255), ccv varchar(255), payment_status integer, status integer, basket_id bigint, primary key (id)) [42001-200]
2022-04-28 16:13:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "ALTER TABLE ORDER[*] ADD CONSTRAINT FKI9DEIURYIQ9CD1U2FQS4QVKRR FOREIGN KEY (BASKET_ID) REFERENCES BASKET"; expected "identifier"; SQL statement:
alter table order add constraint FKi9deiuryiq9cd1u2fqs4qvkrr foreign key (basket_id) references basket [42001-200]
2022-04-28 16:14:18 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 34 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 28 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 29 more
2022-04-28 16:14:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "DROP TABLE IF EXISTS ORDER[*] CASCADE "; expected "identifier"; SQL statement:
drop table if exists order CASCADE  [42001-200]
2022-04-28 16:14:44 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 34 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 28 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 29 more
2022-04-28 16:14:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "DROP TABLE IF EXISTS ORDER[*] CASCADE "; expected "identifier"; SQL statement:
drop table if exists order CASCADE  [42001-200]
2022-04-28 16:52:22 jdbc[13]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'INIT' (CUSTOMER_ORDER: ""STATUS"" INTEGER)"; SQL statement:
UPDATE "PUBLIC"."CUSTOMER_ORDER" SET "ID"=? ,"CREATED_AT"=? ,"CREATED_BY"=? ,"DELETED_AT"=? ,"DELETED_BY"=? ,"IS_DELETED"=? ,"UPDATED_AT"=? ,"UPDATED_BY"=? ,"CARD_LAST_DATE"=? ,"CARD_NUMBER"=? ,"CARD_OWNER_NAME"=? ,"CCV"=? ,"PAYMENT_STATUS"=? ,"STATUS"=? ,"BASKET_ID"=?  WHERE "ID"=? [22018-200]
2022-04-28 16:52:22 jdbc[13]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'INIT' (CUSTOMER_ORDER: ""STATUS"" INTEGER)"; SQL statement:
UPDATE "PUBLIC"."CUSTOMER_ORDER" SET "ID"=? ,"CREATED_AT"=? ,"CREATED_BY"=? ,"DELETED_AT"=? ,"DELETED_BY"=? ,"IS_DELETED"=? ,"UPDATED_AT"=? ,"UPDATED_BY"=? ,"CARD_LAST_DATE"=? ,"CARD_NUMBER"=? ,"CARD_OWNER_NAME"=? ,"CCV"=? ,"PAYMENT_STATUS"=? ,"STATUS"=? ,"BASKET_ID"=?  WHERE "ID"=? [22018-200]
2022-04-28 16:52:43 jdbc[13]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'INIT' (CUSTOMER_ORDER: ""STATUS"" INTEGER)"; SQL statement:
UPDATE "PUBLIC"."CUSTOMER_ORDER" SET "ID"=? ,"CREATED_AT"=? ,"CREATED_BY"=? ,"DELETED_AT"=? ,"DELETED_BY"=? ,"IS_DELETED"=? ,"UPDATED_AT"=? ,"UPDATED_BY"=? ,"CARD_LAST_DATE"=? ,"CARD_NUMBER"=? ,"CARD_OWNER_NAME"=? ,"CCV"=? ,"PAYMENT_STATUS"=? ,"STATUS"=? ,"BASKET_ID"=?  WHERE "ID"=? [22018-200]
2022-04-28 16:52:43 jdbc[13]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'INIT' (CUSTOMER_ORDER: ""STATUS"" INTEGER)"; SQL statement:
UPDATE "PUBLIC"."CUSTOMER_ORDER" SET "ID"=? ,"CREATED_AT"=? ,"CREATED_BY"=? ,"DELETED_AT"=? ,"DELETED_BY"=? ,"IS_DELETED"=? ,"UPDATED_AT"=? ,"UPDATED_BY"=? ,"CARD_LAST_DATE"=? ,"CARD_NUMBER"=? ,"CARD_OWNER_NAME"=? ,"CCV"=? ,"PAYMENT_STATUS"=? ,"STATUS"=? ,"BASKET_ID"=?  WHERE "ID"=? [22018-200]
2022-04-28 16:52:49 jdbc[13]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'INIT' (CUSTOMER_ORDER: ""STATUS"" INTEGER)"; SQL statement:
UPDATE "PUBLIC"."CUSTOMER_ORDER" SET "ID"=? ,"CREATED_AT"=? ,"CREATED_BY"=? ,"DELETED_AT"=? ,"DELETED_BY"=? ,"IS_DELETED"=? ,"UPDATED_AT"=? ,"UPDATED_BY"=? ,"CARD_LAST_DATE"=? ,"CARD_NUMBER"=? ,"CARD_OWNER_NAME"=? ,"CCV"=? ,"PAYMENT_STATUS"=? ,"STATUS"=? ,"BASKET_ID"=?  WHERE "ID"=? [22018-200]
2022-04-28 16:52:49 jdbc[13]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'INIT' (CUSTOMER_ORDER: ""STATUS"" INTEGER)"; SQL statement:
UPDATE "PUBLIC"."CUSTOMER_ORDER" SET "ID"=? ,"CREATED_AT"=? ,"CREATED_BY"=? ,"DELETED_AT"=? ,"DELETED_BY"=? ,"IS_DELETED"=? ,"UPDATED_AT"=? ,"UPDATED_BY"=? ,"CARD_LAST_DATE"=? ,"CARD_NUMBER"=? ,"CARD_OWNER_NAME"=? ,"CCV"=? ,"PAYMENT_STATUS"=? ,"STATUS"=? ,"BASKET_ID"=?  WHERE "ID"=? [22018-200]
2022-04-28 16:53:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'PAYMENT_SUCCESS' (CUSTOMER_ORDER: ""PAYMENT_STATUS"" INTEGER)"; SQL statement:
insert into customer_order (id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, basket_id, card_last_date, card_number, card_owner_name, ccv, payment_status, status) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22018-200]
2022-04-28 17:55:31 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 34 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/AEO/Desktop/172_Norma_Java_Spring_Bootcamp/fourth-week-homework-aozcann/h2/mydb.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 28 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 29 more
2022-05-01 00:04:55 jdbc[85]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 19 more
2022-05-01 11:30:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE CAMPAIGN (ID BIGINT GENERATED BY DEFAULT AS IDENTITY, CREATED_AT TIMESTAMP, CREATED_BY VARCHAR(50), DELETED_AT TIMESTAMP, DELETED_BY VARCHAR(50), IS_DELETED BOOLEAN NOT NULL, UPDATED_AT TIMESTAMP, UPDATED_BY VARCHAR(50), CODE VARCHAR(255), DISCOUNT DECIMAL(19,2), END_DATE TIMESTAMP, LIMIT[*] DECIMAL(19,2), NAME VARCHAR(255), START_DATE TIMESTAMP, TYPE INTEGER, PRIMARY KEY (ID))"; expected "identifier"; SQL statement:
create table campaign (id bigint generated by default as identity, created_at timestamp, created_by varchar(50), deleted_at timestamp, deleted_by varchar(50), is_deleted boolean not null, updated_at timestamp, updated_by varchar(50), code varchar(255), discount decimal(19,2), end_date timestamp, limit decimal(19,2), name varchar(255), start_date timestamp, type integer, primary key (id)) [42001-200]
